### ISSUE TITLE
think I'm missing something ...

### ISSUE THREAD

**Issue by emckean** [sloria/AreYouSure.js#1]
Hi! areyousure.js seems to be just what I'm looking for. 

I'm trying to add it to a Node project, in an .ejs file. The line is:

```
"<li><a href="/deleteList/<%= data.listInfo.permalink %>" data-areyousure >Delete</a></li>
```

But, nada. What am I missing? 

I have npm-installed it and confirmed it's in the node_modules directory. Is there a "require" step? 

Any help gratefully received, and I'll volunteer to update the docs if there is in fact a step missing. :-)

**Comment by sloria** [comment]
There should be no require step. For the "autodiscover" feature to work, areyousure.js must be executed, or you can trigger it programmatically like so:

``` javascript
AreYouSure.discover();
```
